export const components = [
  {
    type: "gate",
    name: "BabyDan Premier True Pressure Fit Safety Gate - White (73.5 - 79.6cm)",
    width: 76,
    price: 76,
    id: 1,
    img: "./images/gate.webp",
    isExtension: false,
    tolerance: 6,
  },
  {
    type: "extension",
    name: "BabyDan Premier Gate Extension 64.5cm",
    width: 64,
    price: 64,
    id: 2,
    img: "./images/largeExtension.jpg",
    isExtension: true,
    tolerance: 0,
  },
  {
    type: "extension",
    name: "Babydan Premier Gate Extension 32cm",
    width: 32,
    price: 32,
    id: 3,
    img: "./images/medExtension.jpg",
    isExtension: true,
    tolerance: 0,
  },
  {
    type: "extension",
    name: "BabyDan Standard Extend-A-Gate Kit - White ( 7cm)",
    width: 7,
    price: 7,
    id: 4,
    img: "./images/smallExtension.jpg",
    isExtension: true,
    tolerance: 0,
  },
];
